## clock topic
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"

## cmd vel topic
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"

## lidar scan topic
- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"

## pointcloud topic
# - ros_topic_name: "/pointcloud"
#   gz_topic_name: "/lidar/points"
#   ros_type_name: "sensor_msgs/msg/PointCloud2"
#   gz_type_name: "ignition.msgs.PointCloudPacked"